<a href="https://colab.research.google.com/github/drivema/google_colab/blob/master/firstlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a * 7)
print(a)
print(a*3)
print(a*4)

[ 7 14 21 28 35]
[1 2 3 4 5]
[ 3  6  9 12 15]
[ 4  8 12 16 20]
